project_id = "ypkmorgcpooygsvhcpvo"

[functions.get_public_properties]
verify_jwt = false

[functions.real-estate-chat]
verify_jwt = false

[functions.search-properties]
verify_jwt = false

[functions.send-chat-message]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false